org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.213
neo_version_range=[21.1,21.2)
loader_version_range=[1,)
mod_id=oneblockreborn
mod_name=One-Block Reborn
mod_license=One-Block Reborn Custom License
mod_version=0.7.19
mod_group_id=ru.sn0w1.oneblockreborn
mod_authors=SN0W1
mod_description=Per-player One-Block Reborn progression with configurable stages.
